apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'employee-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['employee-service.employee-app.svc.cluster.local:8080']